/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.group2project.gamingplatformgui;

import oldClasses.UserSession;

import javax.swing.*;
import java.util.HashMap;
import java.util.Map;

/**
 *
 *
 * @author Jeremy
 */
public class ReportsPage extends javax.swing.JFrame {
    private Integer userID;
    private Boolean editReport;
    private SQLConnection conn = SQLConnection.getInstance();

    /** Creates new form GamesPage */
    public ReportsPage() {
        initComponents();
        updateUserName();
        this.editReport = false;
        lockFields();
        updateReportList();
    }
    public ReportsPage(Integer userID) {
        this.userID = userID;
        initComponents();
        this.editReport = false;
        lockFields();
        updateReportList();
        setUsernameText(userID);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reviewsScrollPane = new javax.swing.JScrollPane();
        reportList = new javax.swing.JList<>();
        pageTitleLabel = new javax.swing.JLabel();
        submitReportButton = new javax.swing.JButton();
        reportIDLabel = new javax.swing.JLabel();
        offenderNameLabel = new javax.swing.JLabel();
        reportStatusLabel = new javax.swing.JLabel();
        reportStatusPendingResolvedLabel = new javax.swing.JLabel();
        offenderNameTextField = new javax.swing.JTextField(5);
        backButton = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        reportContentScrollPane = new javax.swing.JScrollPane();
        reportTextPane = new javax.swing.JTextPane();
        reportContentLabel = new javax.swing.JLabel();
        reportIDValueLabel = new javax.swing.JLabel();
        myReportsLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reportList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        reportList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reportListValueChanged(evt);
            }
        });
        reviewsScrollPane.setViewportView(reportList);

        pageTitleLabel.setText("Reports");

        submitReportButton.setText("Submit");
        submitReportButton.setActionCommand("buy");
        submitReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitReportButtonActionPerformed(evt);
            }
        });

        reportIDLabel.setText("ReportID:");

        offenderNameLabel.setText("OffenderID:");

        reportStatusLabel.setText("Report Status:");

        reportStatusPendingResolvedLabel.setText("   ");

        offenderNameTextField.setText("   ");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        userNameLabel.setText("UserName");

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        reportTextPane.setText("   ");
        reportContentScrollPane.setViewportView(reportTextPane);

        reportContentLabel.setText("Report Content:");

        reportIDValueLabel.setText("IdNum");

        myReportsLabel.setText("My Reports:");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton)
                            .addComponent(reviewsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(reportContentScrollPane)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(reportStatusLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(reportIDLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(reportIDValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(reportContentLabel))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(reportStatusPendingResolvedLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(offenderNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(offenderNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editButton)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newButton)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pageTitleLabel)
                                .addGap(162, 162, 162)
                                .addComponent(userNameLabel)
                                .addGap(10, 10, 10))
                            .addComponent(submitReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myReportsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageTitleLabel)
                    .addComponent(userNameLabel))
                .addGap(12, 12, 12)
                .addComponent(myReportsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportIDLabel)
                            .addComponent(offenderNameLabel)
                            .addComponent(reportIDValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(offenderNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportStatusPendingResolvedLabel)
                            .addComponent(reportStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(reportContentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(reportContentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editButton)
                                .addGap(5, 5, 5)
                                .addComponent(deleteButton))))
                    .addComponent(reviewsScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitReportButton)
                    .addComponent(backButton))
                .addGap(15, 15, 15))
        );

        reportIDLabel.getAccessibleContext().setAccessibleName("ReportID");

        getAccessibleContext().setAccessibleName("ReportID");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        this.editReport = false;
        editButton.setEnabled(false);
        deleteButton.setEnabled(false);
        clearForm();
        reportIDValueLabel.setText(String.valueOf(conn.getNewReportID()));
        unlockFields();
    }//GEN-LAST:event_newButtonActionPerformed

    private void submitReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitReportButtonActionPerformed
        submitReport();
        lockFields();
    }//GEN-LAST:event_submitReportButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose();  // Dispose of the page
                new HomePage().setVisible(true);
            }
        });
    }//GEN-LAST:event_backButtonActionPerformed
    private void submitReport(){
        HashMap<String, String> reportMap = new HashMap();
        reportMap.put("reportID", reportIDValueLabel.getText());
        reportMap.put("reporterID", String.valueOf(userID));
        String offenderID = conn.getPlayerIdByUsername(offenderNameTextField.getText().toLowerCase());
        reportMap.put("offenderID", offenderID);
        reportMap.put("reportDesc", reportTextPane.getText());
        reportMap.put("reportStatus", "Pending");
        for (Map.Entry<String, String> entry : reportMap.entrySet()) {
            if (entry.getValue() == null) {
                if (entry.getKey().equals("offenderID")){
                    JOptionPane.showMessageDialog(null, "Error! Offender username not found.", "Input Error", JOptionPane.ERROR_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Error: " + entry.getKey() + " is null.", "Input Error", JOptionPane.ERROR_MESSAGE);
                }
                return;
            }
        }
        if (!editReport){
            conn.insertReport(reportMap);
        }
        else{
            conn.updateReport(reportMap);
        }
        updateReportList();
    }
    private void deleteReport(){
        conn.deleteReport(Integer.parseInt(reportIDValueLabel.getText()));
        updateReportList();
    }
    private void reportListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reportListValueChanged
        lockFields();
        editButton.setEnabled(true);
        deleteButton.setEnabled(true);
        int index = reportList.getSelectedIndex();
        int indextest = reportList.getLeadSelectionIndex();
        if (index >= 0) {
//            System.out.println("Index Selected: " + index);
            String s = (String) reportList.getSelectedValue();
//            System.out.println("Value Selected: " + s);
            String[] parts = s.split("-");
            Integer reportID = Integer.parseInt(parts[0].trim());
//            System.out.println("reportID: " + reportID);
            updateForm(reportID);
        }else{
            clearForm();
        }
    }//GEN-LAST:event_reportListValueChanged
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteReport();
    }//GEN-LAST:event_deleteButtonActionPerformed
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        this.editReport = true;
        unlockFields();
    }//GEN-LAST:event_editButtonActionPerformed
    public void updateReportList(){
        DefaultListModel listModel;
        listModel = conn.getReportList(userID);
        reportList.setModel(listModel);
    }
    public void updateForm(Integer reportID){
        HashMap reportContents = conn.getReport(reportID);
        reportIDValueLabel.setText(Integer.toString(reportID));
        Integer offenderID = Integer.parseInt(reportContents.get("OffenderID").toString());
        String offenderUsername = conn.getUsernameByPlayerID(offenderID);
        offenderNameTextField.setText(offenderUsername);
        reportStatusPendingResolvedLabel.setText(reportContents.get("ReportStatus").toString());
        reportTextPane.setText(reportContents.get("ReportDesc").toString());
    }
    public void setUsernameText(Integer playerID){
        String userName = conn.getUsernameByPlayerID(playerID);
        userNameLabel.setText(userName);
    }
    private void updateUserName() {
        String username = UserSession.getInstance().getUsername(); // Retrieve the username from the session
        if (username != null && !username.isEmpty()) {
            this.userID = Integer.parseInt(conn.getPlayerIdByUsername(username));
            userNameLabel.setText(username); // Set the username on the label
        } else {
            userNameLabel.setText("Guest"); // Default text or handling for not logged-in users
        }
    }
    public void clearForm(){
        reportIDValueLabel.setText(null);
        offenderNameTextField.setText(null);
        reportStatusPendingResolvedLabel.setText(null);
        reportTextPane.setText(null);
        lockFields();
    }
    public void lockFields(){
        reportIDValueLabel.setEnabled(false);
        offenderNameTextField.setEnabled(false);
        reportStatusPendingResolvedLabel.setEnabled(false);
        reportTextPane.setEnabled(false);
        submitReportButton.setEnabled(false);
        editButton.setEnabled(false);
        deleteButton.setEnabled(false);
    }
    public void unlockFields(){
        reportIDValueLabel.setEnabled(true);
        offenderNameTextField.setEnabled(true);
        reportStatusPendingResolvedLabel.setEnabled(true);
        reportTextPane.setEnabled(true);
        submitReportButton.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel myReportsLabel;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel offenderNameLabel;
    private javax.swing.JTextField offenderNameTextField;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JLabel reportContentLabel;
    private javax.swing.JScrollPane reportContentScrollPane;
    private javax.swing.JLabel reportIDLabel;
    private javax.swing.JLabel reportIDValueLabel;
    private javax.swing.JList<String> reportList;
    private javax.swing.JLabel reportStatusLabel;
    private javax.swing.JLabel reportStatusPendingResolvedLabel;
    private javax.swing.JTextPane reportTextPane;
    private javax.swing.JScrollPane reviewsScrollPane;
    private javax.swing.JButton submitReportButton;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables

}
